version: 0.2

env:
  variables:
    AWS_REGION_2: "us-east-1"
    REACT_APP_API_SERVICE_URL: "http://flask-react-alb2-146681863.us-east-1.elb.amazonaws.com"
    WEBAPP_API_SERVICE_URL: "x-927433976.us-east-1.elb.amazonaws.com"
  parameter-store:
    DOCKERHUB_USERNAME: "/CodeBuild/DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "/CodeBuild/DOCKERHUB_PASSWORD"

phases:
  pre_build:
    commands:
      - echo "Logging in to container registries..."
      - >
        docker login --username $DOCKERHUB_USERNAME --password-stdin <<< "$DOCKERHUB_PASSWORD"
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo building dev images...
      - docker-compose up -d --build
      - echo building prod images...
      - >
        docker build \
        -f depth-anything-flask-app/Dockerfile \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mlops/depth-anything-flask-app:prod \
        ./depth-anything-flask-app
      - >
        docker build \
        -f object-detection-react-app/Dockerfile \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mlops/object-detection-react-app:prod \
        ./object-detection-react-app
      - >
        docker build \
        -f yolo-v5-flask-app/Dockerfile \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mlops/yolo-v5-flask-app:prod \
        ./yolo-v5-flask-app
      - echo prod images built successfully
  post_build:
    commands:
      - echo pushing prod images to ecr...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mlops/depth-anything-flask-app:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mlops/object-detection-react-app:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mlops/yolo-v5-flask-app:prod
      - echo prod images pushed successfully
